/*
-- Query: SELECT 
    vendor_name,
    vendor_contact_last_name,
    vendor_contact_first_name
FROM
    vendors
ORDER BY vendor_contact_last_name ASC , vendor_contact_first_name ASC
LIMIT 0, 1000

-- Date: 2023-10-31 11:29
*/
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Dristas Groom & McCormick','Aaronsen','Thom');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Internal Revenue Service','Aileen','Joan');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('US Postal Service','Alberto','Francesco');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Yale Industrial Trucks-Fresno','Alexis','Alexandro');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Leslie Company','Alondra','Zev');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('American Booksellers Assoc','Angelica','Nashalie');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Courier Companies, Inc','Antavius','Troy');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Pacific Gas & Electric','Anthoni','Kaitlyn');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Lou Gentile\'s Flower Basket','Anum','Trisha');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Pollstar','Aranovitch','Robert');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Compuserve','Armando','Jan');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Data Reproductions Corp','Arodondo','Cesar');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('State of California','Articunia','Mercedez');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Computer Library','Aryn','Leroy');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Fresno Rack & Shelving Inc','Baylee','Dakota');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('United Parcel Service','Beauregard','Violet');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Nat Assoc of College Stores','Bernard','Lucy');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Baker & Taylor Books','Bernardo','Brittnee');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Golden Eagle Insurance Co','Blanca','Korah');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Unocal','Bluzinski','Rachael');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Simon Direct Inc','Bradlee','Daniel');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Gostanian General Building','Bragg','Walter');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Fresno Credit Bureau','Braydon','Anne');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Fresno County Tax Collector','Brenton','Kila');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Nielson','Brooklynn','Keely');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Federal Express Corporation','Bucket','Charlie');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('IBM','Camron','Trentin');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Publishers Weekly','Carrollton','Priscilla');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Boucher Communications Inc','Carson','Julian');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Fresno Photoengraving Company','Chaddick','Derek');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Ph Photographic Services','Cheyenne','Kaylea');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Dataforms/West','Church','Charlie');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Champion Printing Company','Clifford','Jillian');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Small Press','Colette','Dusty');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('The Fresno Bee','Colton','Leah');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Open Horizons Publishing','Damien','Deborah');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Wells Fargo Bank','Damion','Mikayla');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Executive Office Products','Danielson','Rachael');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('ASC Signs','Darien','Elisabeth');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('State Board Of Equalization','Dean','Julissa');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Bill Jones','Deasia','Tristin');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('McKesson Water Products','Destin','Luciano');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Retirement Plan Consultants','Edgardo','Salina');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Blue Cross','Eliana','Nikolas');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Digital Dreamworks','Elmert','Ron');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('RR Bowker','Essence','Marjorie');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Cardinal Business Media, Inc.','Eulalia','Kelsey');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Micro Center','Evan','Emily');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Postmaster','Finklestein','Fyodor');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Abbey Office Furnishings','Francis','Kyra');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Naylor Publications Inc','Gerald','Kristofer');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Aztek Label','Griffin','Brian');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Zee Medical Service Co','Hallie','Juliana');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Edward Data Services','Helena','Jeanette');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Yesmed, Inc','Hernandez','Reba');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Mcgraw Hill Companies','Holbrooke','Rashad');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Bill Marvin Electric Inc','Hostlery','Kaitlin');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Cal State Termite','Hunter','Demetrius');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('National Information Data Ctr','Irvin','Ania');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Cahners Publishing Company','Jacobsen','Samuel');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Gary McKeighan Insurance','Jair','Caitlin');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Costco','Jaquan','Aaron');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Zip Print & Copy Center','Javen','Justin');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Dean Witter Reynolds','Johnson','Vance');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('California Data Marketing','Jonessen','Moises');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('DMV Renewal','Josey','Lorena');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('BFI Industries','Kaleigh','Erick');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Wang Laboratories, Inc.','Kapil','Robert');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Blanchard & Johnson Associates','Keeton','Gonzalo');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Shields Design','Kerry','Rowan');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Net Asset, Llc','Kraggin','Laura');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('The Mailers Guide Co','Lacy','Karina');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Diversified Printing & Pub','Lane','Vanesa');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Enterprise Communications Inc','Lawrence','Eileen');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Robbins Mobile Lock And Key','Leigh','Bill');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Ascom Hasler Mailing Systems','Lewis','Darnell');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Register of Copyrights','Liana','Lukas');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Computerworld','Lloyd','Angel');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Towne Advertiser\'s Mailing Svcs','Maegen','Ted');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Springhouse Corp','Maeve','Clarence');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('The Presort Center','Marissa','Kyle');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Newbrige Book Clubs','Marks','Michelle');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('The Library Ltd','Marques','Malia');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('California Chamber Of Commerce','Mauro','Anton');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Capital Resource Credit','Maxwell','Jayda');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('City Of Fresno','Mayte','Kendall');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('The Drawing Board','Mckayla','Jeffery');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Frank E Wilber Co','Millerton','Johnathon');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Quality Education Data','Misael','Kayle');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Custom Printing Company','Myles','Harley');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Venture Communications Int\'l','Neftaly','Thalia');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Rich Advertising','Neil','Ingrid');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Pacific Bell','Nickalus','Kurt');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Texaco','Oren','Grace');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Opamp Technical Books','Paris','Gideon');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Office Depot','Pinsippi','Val');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Bertelsmann Industry Svcs. Inc','Potter','Lance');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Franchise Tax Board','Prado','Anita');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Jobtrak','Quinn','Kenzie');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Expedata Inc','Quintin','Marvin');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Cmg Information Services','Randall','Yash');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Crown Printing','Randrup','Leann');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Vision Envelope & Printing','Raven','Jamari');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Malloy Lithographing Inc','Regging','Abe');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Reiter\'s Scientific & Pro Books','Rodolfo','Carlee');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('California Business Machines','Rohansen','Anders');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Zylka Design','Ronaldsen','Jaime');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Wakefield Co','Rothman','Nathanael');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Evans Executone Inc','Royce','Hannah');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Blue Shield of California','Smith','Kylie');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Roadway Package System, Inc','Smith','Sam');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Coffee Break Service','Smitzen','Jeffrey');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Ford Motor Credit Company','Snyder','Karen');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Suburban Propane','Spivak','Harold');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Kent H Landsberg Co','Stevens','Wendy');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('American Express','Story','Kirsten');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Graylift','Sydney','Deangelo');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Publishers Marketing Assoc','Walker','Jovon');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Valprint','Warren','Quentin');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('AT&T','Wesley','Alisha');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('The Windows Deck','Wood','Liam');
INSERT INTO `` (`vendor_name`,`vendor_contact_last_name`,`vendor_contact_first_name`) VALUES ('Ingram','Yobani','Trey');
